version: "3.5"

services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  API_server:
    container_name: API_server
    image: asset-registry:latest
    ports:
      - "127.0.0.1:7070:80/tcp"
    command: >
      --basicAuthUser=admin
      --basicAuthPassword=secret
    depends_on: 
      - mongodb_container

volumes:
    mongodb_data_container: